"""initial schema

Revision ID: 24afe70f452f
Revises: 
Create Date: 2026-05-13 18:51:32.072115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24afe70f452f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dmas_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('unions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dma_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('media_emails', sa.JSON(), nullable=True),
    sa.Column('media_linkedin', sa.String(length=500), nullable=True),
    sa.Column('apprenticeship_emails', sa.JSON(), nullable=True),
    sa.Column('apprenticeship_linkedin', sa.String(length=500), nullable=True),
    sa.Column('apprenticeship_phone', sa.String(length=200), nullable=True),
    sa.Column('general_phone', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('application_window', sa.String(length=500), nullable=True),
    sa.Column('next_application_window', sa.String(length=500), nullable=True),
    sa.Column('application_window_status', sa.String(length=50), nullable=True),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('application_instructions', sa.Text(), nullable=True),
    sa.Column('apprentice_starting_wage', sa.String(length=200), nullable=True),
    sa.Column('journeyman_wage', sa.String(length=200), nullable=True),
    sa.Column('wage_notes', sa.Text(), nullable=True),
    sa.Column('program_length', sa.String(length=200), nullable=True),
    sa.Column('requirements_summary', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.String(length=20), nullable=True),
    sa.Column('extraction_notes', sa.Text(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('scrape_status', sa.String(length=30), nullable=True),
    sa.Column('admin_verified', sa.Boolean(), nullable=True),
    sa.Column('awaiting_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dma_id'], ['dmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unions_admin_verified'), ['admin_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_unions_awaiting_review'), ['awaiting_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_unions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_unions_dma_id'), ['dma_id'], unique=False)

    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('union_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['union_id'], ['unions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_jobs_union_id'), ['union_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_jobs_union_id'))
        batch_op.drop_index(batch_op.f('ix_scrape_jobs_status'))

    op.drop_table('scrape_jobs')
    with op.batch_alter_table('unions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unions_dma_id'))
        batch_op.drop_index(batch_op.f('ix_unions_category'))
        batch_op.drop_index(batch_op.f('ix_unions_awaiting_review'))
        batch_op.drop_index(batch_op.f('ix_unions_admin_verified'))

    op.drop_table('unions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('dmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dmas_slug'))

    op.drop_table('dmas')
    # ### end Alembic commands ###
